package com.bindi.collegeplanner.databaseClasses;

import java.util.ArrayList;

public class CollegeDb {

    private ArrayList<String> collegesList;

    public CollegeDb(){
        collegesList = new ArrayList<String>();
        collegesList.add("Adelphi University");
        collegesList.add("Adrian College");
        collegesList.add("Agnes Scott College");
        collegesList.add("University of Alabama");
        collegesList.add("University of Alabama A&M");
        collegesList.add("University of Alabama Birmingham");
        collegesList.add("University of Alabama Huntsville");
        collegesList.add("Albion College");
        collegesList.add("Albright College");
        collegesList.add("Alfred University");
        collegesList.add("Allegheny College");
        collegesList.add("Amherst College");
        collegesList.add("Andrews University");
        collegesList.add("Antioch College");
        collegesList.add("American International College");
        collegesList.add("American University");
        collegesList.add("Appalachian State University");
        collegesList.add("University of Arizona");
        collegesList.add("Arizona State University");
        collegesList.add("ArtCenter College of Design");
        collegesList.add("Ashland University");
        collegesList.add("University of Arkansas");
        collegesList.add("Assumption College");
        collegesList.add("College of the Atlantic");
        collegesList.add("Auburn University");
        collegesList.add("Augusta University");
        collegesList.add("Augustana University");
        collegesList.add("Augustana College");
        collegesList.add("Auburn University");
        collegesList.add("Austin College");
        collegesList.add("Azusa Pacific University");

        collegesList.add("Babson College");
        collegesList.add("Baldwin Wallace University");
        collegesList.add("Ball State University");
        collegesList.add("Bard College");
        collegesList.add("Barnard College");
        collegesList.add("Barry University");
        collegesList.add("Baruch College");
        collegesList.add("Bates College");
        collegesList.add("Baylor University");
        collegesList.add("Becker College");
        collegesList.add("Bellarmine University");
        collegesList.add("Belmont Abbey College");
        collegesList.add("Belmont University");
        collegesList.add("Beloit College");
        collegesList.add("Benedictine University");
        collegesList.add("Bennett College");
        collegesList.add("Bennington College");
        collegesList.add("Bentley University");
        collegesList.add("Berea College");
        collegesList.add("Berklee College of Music");
        collegesList.add("Berry College");
        collegesList.add("Biola University");
        collegesList.add("Birmingham Southern College");
        collegesList.add("Bloomsburg University");
        collegesList.add("Blue Mountain College");
        collegesList.add("Boise State University");
        collegesList.add("Boston College");
        collegesList.add("Boston University");
        collegesList.add("Bowdoin College");
        collegesList.add("Bowling Green State University");
        collegesList.add("Bradley University");
        collegesList.add("Brandeis University");
        collegesList.add("Brigham Young University");
        collegesList.add("University of British Columbia");
        collegesList.add("Brooklyn College");
        collegesList.add("Brown University");
        collegesList.add("Bryant University");
        collegesList.add("Bryn Mawr College");
        collegesList.add("Bucknell University");
        collegesList.add("Butler University");

        collegesList.add("Caldwell University");
        collegesList.add("California College of the Arts");
        collegesList.add("California Institute of Technology");
        collegesList.add("California Institute of the Arts");
        collegesList.add("California Northstate University");
        collegesList.add("California Polytechnic State University");
        collegesList.add("California State Polytechnic University, Pomona");
        collegesList.add("University of California");
        collegesList.add("University of California - Berkeley");
        collegesList.add("University of California - Davis");
        collegesList.add("University of California - Irvine");
        collegesList.add("University of California - Los Angeles");
        collegesList.add("University of California - Merced");
        collegesList.add("University of California - Riverside");
        collegesList.add("University of California - San Diego");
        collegesList.add("University of California - Santa Barbara");
        collegesList.add("University of California - Santa Cruz");
        collegesList.add("California Lutheran University");
        collegesList.add("California State University | CSU");
        collegesList.add("California State University - East Bay");
        collegesList.add("California State University - Fresno");
        collegesList.add("California State University - Fullerton");
        collegesList.add("California State University - Long Beach");
        collegesList.add("California State University - Los Angeles");
        collegesList.add("California State University - Monterey Bay");
        collegesList.add("California State University - Northridge");
        collegesList.add("California State University - Stanislaus");
        collegesList.add("Campbell University");
        collegesList.add("Capital University");
        collegesList.add("Cardinal Stritch University");
        collegesList.add("Carleton College");
        collegesList.add("Carnegie Mellon University");
        collegesList.add("Caroll College");
        collegesList.add("Carthage College");
        collegesList.add("Case Western Reserve University");
        collegesList.add("Catawba College");
        collegesList.add("Catholic University of America");
        collegesList.add("Cazenovia College");
        collegesList.add("Cedar Crest College");
        collegesList.add("Central Connecticut State University");
        collegesList.add("Central Michigan University");
        collegesList.add("Central Washington University");
        collegesList.add("University of Central Florida");
        collegesList.add("Centre College");
        collegesList.add("Champlain College");
        collegesList.add("Chapman University");
        collegesList.add("University of Chicago");
        collegesList.add("Christopher Newport University");
        collegesList.add("University of Cincinnati");
        collegesList.add("City College of New York");
        collegesList.add("Claremont McKenna College");
        collegesList.add("Clark Atlanta University");
        collegesList.add("Clark University");
        collegesList.add("Clarkson University");
        collegesList.add("Clemson University");
        collegesList.add("Cleveland State University");
        collegesList.add("Coastal Carolina University");
        collegesList.add("Coe College");
        collegesList.add("Colby College");
        collegesList.add("Colgate University");
        collegesList.add("College of Charleston");
        collegesList.add("College of St. Benedict");
        collegesList.add("College of William & Mary");
        collegesList.add("College of Wooster");
        collegesList.add("College of the Atlantic");
        collegesList.add("College of the Holy Cross");
        collegesList.add("College of the Ozarks");
        collegesList.add("University of Colorado");
        collegesList.add("Colorado College");
        collegesList.add("Colorado School of Mines");
        collegesList.add("Colorado State University");
        collegesList.add("Columbia College Chicago");
        collegesList.add("Columbia University");
        collegesList.add("Concordia College");
        collegesList.add("Concordia University");
        collegesList.add("University of Connecticut");
        collegesList.add("Connecticut College");
        collegesList.add("Cooper Union");
        collegesList.add("Cornell College");
        collegesList.add("Cornell University");
        collegesList.add("Creighton University");
        collegesList.add("CUNY System");
        collegesList.add("Curry College");

        collegesList.add("Dallas Baptist University");
        collegesList.add("Dartmouth College");
        collegesList.add("Davidson College");
        collegesList.add("University of Dayton");
        collegesList.add("Deep Springs College");
        collegesList.add("University of Delaware");
        collegesList.add("Denison University");
        collegesList.add("University of Denver");
        collegesList.add("DePaul University");
        collegesList.add("DePauw University");
        collegesList.add("Denison University");
        collegesList.add("Dickinson College");
        collegesList.add("Dillard University");
        collegesList.add("Dordt College");
        collegesList.add("Dominican University of California");
        collegesList.add("Drake University");
        collegesList.add("Drew University");
        collegesList.add("Drexel University");
        collegesList.add("Duke University");
        collegesList.add("Duquesne University");

        collegesList.add("Earlham College");
        collegesList.add("East Carolina University");
        collegesList.add("East Tennessee State University");
        collegesList.add("Eastern Michigan University");
        collegesList.add("Eastern Washington University");
        collegesList.add("Eckerd College");
        collegesList.add("Edgewood College");
        collegesList.add("Elon University");
        collegesList.add("Elizabethtown College");
        collegesList.add("Elmhurst College");
        collegesList.add("Elon University");
        collegesList.add("Embry-Riddle Aeronautical University");
        collegesList.add("Emerson College");
        collegesList.add("Emmanual College");
        collegesList.add("Emory University");
        collegesList.add("Endicott College");
        collegesList.add("Evergreen State College");

        collegesList.add("Fairfield University");
        collegesList.add("Fairleigh Dickinson University");
        collegesList.add("Fashion Institute of Technology");
        collegesList.add("Fayetteville State University");
        collegesList.add("Fisher College");
        collegesList.add("Fisk University");
        collegesList.add("Flagler College");
        collegesList.add("University of Florida");
        collegesList.add("Florida A&M University");
        collegesList.add("Florida Atlantic University");
        collegesList.add("Florida Institute of Technology");
        collegesList.add("Florida International University");
        collegesList.add("Florida Memorial University");
        collegesList.add("Florida State University");
        collegesList.add("Fordham University");
        collegesList.add("Franciscan University of Steubenville");
        collegesList.add("Franklin W. Olin College of Engineering");
        collegesList.add("Franklin & Marshall College");
        collegesList.add("Furman University");

        collegesList.add("Gallaudet University");
        collegesList.add("George Mason University");
        collegesList.add("George Washington University");
        collegesList.add("Georgetown University");
        collegesList.add("Georgia College");
        collegesList.add("University of Georgia");
        collegesList.add("Georgia Institute of Technology");
        collegesList.add("Georgia State University");
        collegesList.add("Gettysburg College");
        collegesList.add("Goddard College");
        collegesList.add("Golden Gate University");
        collegesList.add("Gonzaga University");
        collegesList.add("Goucher College");
        collegesList.add("Grand Canyon University");
        collegesList.add("Grand Valley State University");
        collegesList.add("Grinnell College");
        collegesList.add("Grove City College");
        collegesList.add("Gustavus Adolphus College");

        collegesList.add("Hanover College");
        collegesList.add("Hamilton College");
        collegesList.add("Hampden-Sydney College");
        collegesList.add("Hampshire College");
        collegesList.add("Hampton University");
        collegesList.add("University of Hartford");
        collegesList.add("Hartwick College");
        collegesList.add("Harvard University");
        collegesList.add("Harvey Mudd College");
        collegesList.add("Haverford College");
        collegesList.add("Hendrix College");
        collegesList.add("High Point University");
        collegesList.add("Hillsdale College");
        collegesList.add("Hiram College");
        collegesList.add("Hobart and William Smith Colleges");
        collegesList.add("Hofstra University");
        collegesList.add("Hollins University");
        collegesList.add("College of the Holy Cross");
        collegesList.add("Hope College");
        collegesList.add("University of Houston");
        collegesList.add("Howard Payne University");
        collegesList.add("Howard University");
        collegesList.add("Humboldt State University");

        collegesList.add("University of Illinois - Chicago");
        collegesList.add("University of Illinois - Urbana-Champaign");
        collegesList.add("Indiana University - Bloomington");
        collegesList.add("Indiana University - Northwest");
        collegesList.add("Indiana University of Pennsylvania");
        collegesList.add("Indiana University-Purdue University Indianapolis");
        collegesList.add("Indiana University - South Bend");
        collegesList.add("Indiana State University");
        collegesList.add("University of Iowa");
        collegesList.add("Iowa State University");
        collegesList.add("Illinois Wesleyan University");
        collegesList.add("Illinois Institute of Technology");
        collegesList.add("Illinois State University");
        collegesList.add("Ithaca College");

        collegesList.add("Jackson State University");
        collegesList.add("James Madison University");
        collegesList.add("John Carroll University");
        collegesList.add("Johns Hopkins University");
        collegesList.add("The Juilliard School");
        collegesList.add("Juniata College");

        collegesList.add("Kalamazoo College");
        collegesList.add("University of Kansas");
        collegesList.add("Kansas State University");
        collegesList.add("Kennesaw State University");
        collegesList.add("Kent State University");
        collegesList.add("University of Kentucky");
        collegesList.add("Kenyon College");
        collegesList.add("Knox College");

        collegesList.add("Lafayette College");
        collegesList.add("Laguna College of Art and Design");
        collegesList.add("Lake Forest College");
        collegesList.add("LaSalle University");
        collegesList.add("Lasell College");
        collegesList.add("Lawrence University");
        collegesList.add("Lehigh University");
        collegesList.add("Lewis & Clark College");
        collegesList.add("Linfield College");
        collegesList.add("Louisiana State University");
        collegesList.add("University of Louisville");
        collegesList.add("Loyola University of Chicago");
        collegesList.add("Loyola University - Maryland");
        collegesList.add("Loyola University - New Orleans");
        collegesList.add("Loyola Marymount University");
        collegesList.add("University of Lynchburg");

        collegesList.add("Macalester College");
        collegesList.add("University of Maine");
        collegesList.add("Manhattan College");
        collegesList.add("Manhattanville College");
        collegesList.add("Marietta College");
        collegesList.add("Marist College");
        collegesList.add("Marlboro College");
        collegesList.add("Marquette University");
        collegesList.add("University of Mary Washington");
        collegesList.add("University of Maryland - Baltimore County");
        collegesList.add("University of Maryland - College Park");
        collegesList.add("Marymount Manhattan College");
        collegesList.add("University of Massachusetts - Amherst");
        collegesList.add("University of Massachusetts - Boston");
        collegesList.add("Massachusetts Institute of Technology");
        collegesList.add("McGill University");
        collegesList.add("Mercer University");
        collegesList.add("Merrimack College");
        collegesList.add("University of Miami - Florida");
        collegesList.add("Miami University - Ohio");
        collegesList.add("University of Michigan");
        collegesList.add("Michigan State University");
        collegesList.add("Michigan Technological University");
        collegesList.add("Middlebury College");
        collegesList.add("Mills College");
        collegesList.add("Millsaps College");
        collegesList.add("University of Minnesota");
        collegesList.add("University of Mississippi");
        collegesList.add("Mississippi State University");
        collegesList.add("University of Missouri - Columbia");
        collegesList.add("University of Missouri - Kansas City");
        collegesList.add("Missouri University of Science and Technology");
        collegesList.add("Monmouth University");
        collegesList.add("University of Montana");
        collegesList.add("Montclair State University");
        collegesList.add("Moravian College");
        collegesList.add("Morehouse College");
        collegesList.add("Mount Holyoke College");
        collegesList.add("Muhlenberg College");

        collegesList.add("University of Nebraska");
        collegesList.add("University of Nevada");
        collegesList.add("New College of Florida");
        collegesList.add("New England College");
        collegesList.add("University of New Hampshire");
        collegesList.add("University of New Haven");
        collegesList.add("The College of New Jersey");
        collegesList.add("New Jersey Institute of Technology");
        collegesList.add("New Mexico Institute of Mining & Technology");
        collegesList.add("University of New Mexico");
        collegesList.add("University of New Orleans");
        collegesList.add("New York University");
        collegesList.add("University of North Carolina - Asheville");
        collegesList.add("University of North Carolina - Chapel Hill");
        collegesList.add("University of North Carolina - Charlotte");
        collegesList.add("University of North Carolina - Greensboro");
        collegesList.add("University of North Carolina - Wilmington");
        collegesList.add("North Carolina School of the Arts");
        collegesList.add("North Carolina State University");
        collegesList.add("University of North Dakota");
        collegesList.add("University of North Florida");
        collegesList.add("Northeastern University");
        collegesList.add("Northern Arizona University");
        collegesList.add("Northwestern University");
        collegesList.add("University of Notre Dame");

        collegesList.add("Oberlin College");
        collegesList.add("Occidental College");
        collegesList.add("Oglethorpe University");
        collegesList.add("Ohio University");
        collegesList.add("Ohio Northern University");
        collegesList.add("Ohio State University");
        collegesList.add("Ohio Wesleyan University");
        collegesList.add("University of Oklahoma");
        collegesList.add("Oklahoma State University");
        collegesList.add("Old Dominion University");
        collegesList.add("Olin College");
        collegesList.add("University of Oregon");
        collegesList.add("Oregon State University");

        collegesList.add("Pace University");
        collegesList.add("University of the Pacific");
        collegesList.add("Parsons School of Design");
        collegesList.add("Penn State");
        collegesList.add("University of Pennsylvania");
        collegesList.add("Pepperdine University");
        collegesList.add("Philadelphia University");
        collegesList.add("University of Pittsburgh");
        collegesList.add("Pitzer College");
        collegesList.add("Pomona College");
        collegesList.add("Pratt Institute");
        collegesList.add("Princeton University");
        collegesList.add("Providence College");
        collegesList.add("University of Puget Sound");
        collegesList.add("Purdue University");

        collegesList.add("Queens University - Kingston, Ontario");
        collegesList.add("Quinnipiac University");

        collegesList.add("Randolph College");
        collegesList.add("Randolph-Macon College");
        collegesList.add("University of Redlands");
        collegesList.add("Reed College");
        collegesList.add("Regis University");
        collegesList.add("Rensselaer Polytechnic Institute");
        collegesList.add("University of Rhode Island");
        collegesList.add("Rhode Island School of Design");
        collegesList.add("Rhodes College");
        collegesList.add("Rice University");
        collegesList.add("University of Richmond");
        collegesList.add("Rider University");
        collegesList.add("Ripon College");
        collegesList.add("University of Rochester");
        collegesList.add("Rochester Institute of Technology");
        collegesList.add("Rollins College");
        collegesList.add("Rose-Hulman Institute of Technology");
        collegesList.add("Rowan University");
        collegesList.add("Rutgers University");

        collegesList.add("Sacred Heart University");
        collegesList.add("College of Saint Benedict and Saint John's University");
        collegesList.add("St. Bonaventure University");
        collegesList.add("St. John's College - Maryland");
        collegesList.add("St. John's College - New Mexico");
        collegesList.add("St. John's University (New York)");
        collegesList.add("Saint Joseph's University");
        collegesList.add("St. Lawrence University");
        collegesList.add("Saint Louis University");
        collegesList.add("Saint Mary's College of California");
        collegesList.add("St. Mary's College of Maryland");
        collegesList.add("Saint Mary's College - Notre Dame");
        collegesList.add("Saint Michael's College");
        collegesList.add("Saint Olaf College");
        collegesList.add("Salisbury University");
        collegesList.add("Salve Regina University");
        collegesList.add("Samford University");
        collegesList.add("University of San Diego");
        collegesList.add("San Diego State University");
        collegesList.add("San Francisco State University");
        collegesList.add("University of San Francisco");
        collegesList.add("San Jose State University");
        collegesList.add("Santa Clara University");
        collegesList.add("Sarah Lawrence College");
        collegesList.add("Savannah College of Art and Design");
        collegesList.add("School of Visual Arts");
        collegesList.add("University of Scranton");
        collegesList.add("Saint Anselm College");
        collegesList.add("Scripps College");
        collegesList.add("Seattle University");
        collegesList.add("Seton Hall University");
        collegesList.add("Sewanee: The University of the South");
        collegesList.add("Shimer College");
        collegesList.add("Siena College");
        collegesList.add("Simmons College");
        collegesList.add("Simon's Rock College of Bard");
        collegesList.add("Skidmore College");
        collegesList.add("Smith College");
        collegesList.add("Soka University of America");
        collegesList.add("Sonoma State University");
        collegesList.add("University of South Carolina");
        collegesList.add("University of South Florida");
        collegesList.add("University of Southern California");
        collegesList.add("Southern Methodist University");
        collegesList.add("Southwestern University");
        collegesList.add("Spelman College");
        collegesList.add("Stanford University");
        collegesList.add("Stephens College");
        collegesList.add("Stetson University");
        collegesList.add("Stevens Institute of Technology");
        collegesList.add("Stevenson University");
        collegesList.add("Stonehill College");
        collegesList.add("SUNY at Albany");
        collegesList.add("SUNY at Binghamton");
        collegesList.add("SUNY at Buffalo");
        collegesList.add("SUNY at Geneseo");
        collegesList.add("SUNY at Purchase");
        collegesList.add("SUNY at Stony Brook");
        collegesList.add("Susquehanna University");
        collegesList.add("Swarthmore College");
        collegesList.add("Sweet Briar College");
        collegesList.add("Syracuse University");

        collegesList.add("University of Tampa");
        collegesList.add("Temple University");
        collegesList.add("University of Tennessee");
        collegesList.add("The University of Texas - GENERAL");
        collegesList.add("The University of Texas at Austin");
        collegesList.add("Texas A&M University");
        collegesList.add("TCU");
        collegesList.add("Texas Tech University");
        collegesList.add("Thomas Aquinas College - California");
        collegesList.add("University of Toronto");
        collegesList.add("Towson University");
        collegesList.add("Trinity College (Connecticut)");
        collegesList.add("Trinity University (Texas)");
        collegesList.add("Truman State University");
        collegesList.add("Tufts University");
        collegesList.add("Tulane University");
        collegesList.add("University of Tulsa");
        collegesList.add("Tuskegee University");

        collegesList.add("Union College - New York");
        collegesList.add("United States Air Force Academy");
        collegesList.add("United States Coast Guard Academy");
        collegesList.add("United States Merchant Marine Academy");
        collegesList.add("United States Military Academy");
        collegesList.add("United States Naval Academy");
        collegesList.add("University of the Sciences in Philadelphia");
        collegesList.add("Ursinus College");
        collegesList.add("Ursuline College");
        collegesList.add("University of Utah");

        collegesList.add("Valparaiso University");
        collegesList.add("Vanderbilt University");
        collegesList.add("Vassar College");
        collegesList.add("University of Vermont");
        collegesList.add("Villanova University");
        collegesList.add("University of Virginia");
        collegesList.add("Virginia Commonwealth University");
        collegesList.add("Virginia Tech");
        collegesList.add("Virginia Wesleyan College");

        collegesList.add("Wabash College");
        collegesList.add("Wagner College");
        collegesList.add("Wake Forest University");
        collegesList.add("Warren Wilson College");
        collegesList.add("University of Washington");
        collegesList.add("Washington and Lee University");
        collegesList.add("Washington State University");
        collegesList.add("Washington University in St. Louis");
        collegesList.add("University of Waterloo");
        collegesList.add("Webb Institute");
        collegesList.add("Wellesley College");
        collegesList.add("Wells College");
        collegesList.add("Wesleyan College");
        collegesList.add("Wesleyan University");
        collegesList.add("West Virginia University");
        collegesList.add("Western Michigan University");
        collegesList.add("Western Washington University");
        collegesList.add("Westminster College - Pennsylvania");
        collegesList.add("Wheaton College - Illinois");
        collegesList.add("Wheaton College - Massachusetts");
        collegesList.add("Whitman College");
        collegesList.add("Whittier College");
        collegesList.add("College of William and Mary");
        collegesList.add("Willamette University");
        collegesList.add("William Jewell College");
        collegesList.add("Williams College");
        collegesList.add("University of Wisconsin");
        collegesList.add("Wittenberg University");
        collegesList.add("Wofford College");
        collegesList.add("College of Wooster");
        collegesList.add("Worcester Polytechnic Institute");
        collegesList.add("Wright State University");
        collegesList.add("University of Wyoming");
        collegesList.add("Yale University");
        collegesList.add("Yeshiva University");
        collegesList.add("Xavier University");
    }

    public ArrayList<String> getCollegesList(){
        return collegesList;
    }

}
