package com.bindi.collegeplanner.databaseClasses;

import java.util.ArrayList;

public class CollegeSearchDb {

    private ArrayList<String> collegesList;

    public CollegeSearchDb(){
        collegesList = new ArrayList<String>();
        collegesList.add("Adelphi University");
        collegesList.add("Adrian College");
        collegesList.add("Agnes Scott College");
        collegesList.add("University of Alabama");
        collegesList.add("University of Alabama A&M | AAMU");
        collegesList.add("University of Alabama Birmingham");
        collegesList.add("University of Alabama Huntsville");
        collegesList.add("Albion College");
        collegesList.add("Albright College");
        collegesList.add("Alfred University");
        collegesList.add("Allegheny College");
        collegesList.add("Amherst College");
        collegesList.add("Andrews University");
        collegesList.add("Antioch College");
        collegesList.add("American International College | AIC");
        collegesList.add("American University");
        collegesList.add("Appalachian State University");
        collegesList.add("University of Arizona");
        collegesList.add("Arizona State University | ASU");
        collegesList.add("ArtCenter College of Design | ArtCenter");
        collegesList.add("Ashland University");
        collegesList.add("University of Arkansas");
        collegesList.add("Assumption College");
        collegesList.add("College of the Atlantic");
        collegesList.add("Auburn University");
        collegesList.add("Augusta University");
        collegesList.add("Augustana University");
        collegesList.add("Augustana College");
        collegesList.add("Auburn University");
        collegesList.add("Austin College");
        collegesList.add("Azusa Pacific University | APU");

        collegesList.add("Babson College");
        collegesList.add("Baldwin Wallace University | BW");
        collegesList.add("Ball State University | BSU");
        collegesList.add("Bard College");
        collegesList.add("Barnard College");
        collegesList.add("Barry University");
        collegesList.add("Baruch College | CUNY Baruch");
        collegesList.add("Bates College");
        collegesList.add("Baylor University");
        collegesList.add("Becker College");
        collegesList.add("Bellarmine University");
        collegesList.add("Belmont Abbey College");
        collegesList.add("Belmont University");
        collegesList.add("Beloit College");
        collegesList.add("Benedictine University");
        collegesList.add("Bennett College");
        collegesList.add("Bennington College");
        collegesList.add("Bentley University");
        collegesList.add("Berea College");
        collegesList.add("Berklee College of Music | Berklee");
        collegesList.add("Berry College");
        collegesList.add("Biola University");
        collegesList.add("Birmingham Southern College | BSC");
        collegesList.add("Bloomsburg University | BloomU");
        collegesList.add("Blue Mountain College | BMC");
        collegesList.add("Boise State University | BSU");
        collegesList.add("Boston College | BC");
        collegesList.add("Boston University | BU");
        collegesList.add("Bowdoin College");
        collegesList.add("Bowling Green State University | BGSU");
        collegesList.add("Bradley University");
        collegesList.add("Brandeis University");
        collegesList.add("Brigham Young University | BYU");
        collegesList.add("University of British Columbia");
        collegesList.add("Brooklyn College");
        collegesList.add("Brown University");
        collegesList.add("Bryant University");
        collegesList.add("Bryn Mawr College");
        collegesList.add("Bucknell University");
        collegesList.add("Butler University");

        collegesList.add("Caldwell University");
        collegesList.add("California College of the Arts | CCA");
        collegesList.add("California Institute of Technology | Caltech");
        collegesList.add("California Institute of the Arts | Cal Arts");
        collegesList.add("California Northstate University | CNU");
        collegesList.add("California Polytechnic State University | Cal Poly");
        collegesList.add("California State Polytechnic University, Pomona | Cal Poly Pomona");
        collegesList.add("University of California | UC");
        collegesList.add("University of California - Berkeley | UC Berkeley | UCB");
        collegesList.add("University of California - Davis | UC Davis | UCD");
        collegesList.add("University of California - Irvine | UC Irvine | UCI");
        collegesList.add("University of California - Los Angeles | UC Los Angeles | UCLA");
        collegesList.add("University of California - Merced | UC Merced | UCM");
        collegesList.add("University of California - Riverside | UC Riverside | UCR");
        collegesList.add("University of California - San Diego | UC San Diego | UCSD");
        collegesList.add("University of California - Santa Barbara | UC Santa Barbara | UCSB");
        collegesList.add("University of California - Santa Cruz | UC Sanata Cruz | UCSC");
        collegesList.add("California Lutheran University");
        collegesList.add("California State University | CSU");
        collegesList.add("California State University - East Bay | CSU East Bay");
        collegesList.add("California State University - Fresno | CSU Fresno");
        collegesList.add("California State University - Fullerton | CSU Fullerton");
        collegesList.add("California State University - Long Beach | CSU Long Beach");
        collegesList.add("California State University - Los Angeles | CSU Los Angeles");
        collegesList.add("California State University - Monterey Bay | CSU Monterey Bay");
        collegesList.add("California State University - Northridge | CSU Northridge");
        collegesList.add("California State University - Stanislaus | CSU Stanislaus");
        collegesList.add("Campbell University");
        collegesList.add("Capital University");
        collegesList.add("Cardinal Stritch University");
        collegesList.add("Carleton College");
        collegesList.add("Carnegie Mellon University | CMU");
        collegesList.add("Caroll College");
        collegesList.add("Carthage College");
        collegesList.add("Case Western Reserve University");
        collegesList.add("Catawba College");
        collegesList.add("Catholic University of America | CUA");
        collegesList.add("Cazenovia College");
        collegesList.add("Cedar Crest College");
        collegesList.add("Central Connecticut State University");
        collegesList.add("Central Michigan University | CMU");
        collegesList.add("Central Washington University | CWU");
        collegesList.add("University of Central Florida | UCF");
        collegesList.add("Centre College");
        collegesList.add("Champlain College");
        collegesList.add("Chapman University");
        collegesList.add("University of Chicago");
        collegesList.add("Christopher Newport University | CNU");
        collegesList.add("University of Cincinnati");
        collegesList.add("City College of New York | CCNY");
        collegesList.add("Claremont McKenna College | CMC");
        collegesList.add("Clark Atlanta University");
        collegesList.add("Clark University");
        collegesList.add("Clarkson University");
        collegesList.add("Clemson University");
        collegesList.add("Cleveland State University | CSU");
        collegesList.add("Coastal Carolina University | Coastal");
        collegesList.add("Coe College");
        collegesList.add("Colby College");
        collegesList.add("Colgate University");
        collegesList.add("College of Charleston");
        collegesList.add("College of St. Benedict | CSB");
        collegesList.add("College of William & Mary | William & Mary");
        collegesList.add("College of Wooster");
        collegesList.add("College of the Atlantic | COA");
        collegesList.add("College of the Holy Cross | Holy Cross");
        collegesList.add("College of the Ozarks");
        collegesList.add("University of Colorado");
        collegesList.add("Colorado College");
        collegesList.add("Colorado School of Mines | Mines");
        collegesList.add("Colorado State University | CSU");
        collegesList.add("Columbia College Chicago");
        collegesList.add("Columbia University");
        collegesList.add("Concordia College");
        collegesList.add("Concordia University");
        collegesList.add("University of Connecticut");
        collegesList.add("Connecticut College");
        collegesList.add("Cooper Union");
        collegesList.add("Cornell College");
        collegesList.add("Cornell University");
        collegesList.add("Creighton University");
        collegesList.add("CUNY System");
        collegesList.add("Curry College");

        collegesList.add("Dallas Baptist University | DBU");
        collegesList.add("Dartmouth College");
        collegesList.add("Davidson College");
        collegesList.add("University of Dayton");
        collegesList.add("Deep Springs College");
        collegesList.add("University of Delaware");
        collegesList.add("Denison University");
        collegesList.add("University of Denver");
        collegesList.add("DePaul University");
        collegesList.add("DePauw University");
        collegesList.add("Denison University");
        collegesList.add("Dickinson College");
        collegesList.add("Dillard University");
        collegesList.add("Dordt College");
        collegesList.add("Dominican University of California");
        collegesList.add("Drake University");
        collegesList.add("Drew University");
        collegesList.add("Drexel University");
        collegesList.add("Duke University");
        collegesList.add("Duquesne University");

        collegesList.add("Earlham College");
        collegesList.add("East Carolina University | ECU");
        collegesList.add("East Tennessee State University | ETSU");
        collegesList.add("Eastern Michigan University | EMU");
        collegesList.add("Eastern Washington University | EWU");
        collegesList.add("Eckerd College");
        collegesList.add("Edgewood College");
        collegesList.add("Elon University");
        collegesList.add("Elizabethtown College | E Town");
        collegesList.add("Elmhurst College");
        collegesList.add("Elon University");
        collegesList.add("Embry-Riddle Aeronautical University");
        collegesList.add("Emerson College");
        collegesList.add("Emmanual College");
        collegesList.add("Emory University");
        collegesList.add("Endicott College");
        collegesList.add("Evergreen State College");

        collegesList.add("Fairfield University");
        collegesList.add("Fairleigh Dickinson University");
        collegesList.add("Fashion Institute of Technology");
        collegesList.add("Fayetteville State University | FSU");
        collegesList.add("Fisher College");
        collegesList.add("Fisk University");
        collegesList.add("Flagler College");
        collegesList.add("University of Florida");
        collegesList.add("Florida A&M University | FAMU");
        collegesList.add("Florida Atlantic University | FAU");
        collegesList.add("Florida Institute of Technology | Florida Tech");
        collegesList.add("Florida International University | FIU");
        collegesList.add("Florida Memorial University");
        collegesList.add("Florida State University | FSU");
        collegesList.add("Fordham University");
        collegesList.add("Franciscan University of Steubenville");
        collegesList.add("Franklin W. Olin College of Engineering | Olin");
        collegesList.add("Franklin & Marshall College | F&M");
        collegesList.add("Furman University");

        collegesList.add("Gallaudet University");
        collegesList.add("George Mason University");
        collegesList.add("George Washington University | GW");
        collegesList.add("Georgetown University");
        collegesList.add("Georgia College | GCSU");
        collegesList.add("University of Georgia");
        collegesList.add("Georgia Institute of Technology | Georgia Tech");
        collegesList.add("Georgia State University");
        collegesList.add("Gettysburg College");
        collegesList.add("Goddard College");
        collegesList.add("Golden Gate University");
        collegesList.add("Gonzaga University");
        collegesList.add("Goucher College");
        collegesList.add("Grand Canyon University | GCU");
        collegesList.add("Grand Valley State University | GVSU");
        collegesList.add("Grinnell College");
        collegesList.add("Grove City College");
        collegesList.add("Gustavus Adolphus College");

        collegesList.add("Hanover College");
        collegesList.add("Hamilton College");
        collegesList.add("Hampden-Sydney College | HSC");
        collegesList.add("Hampshire College");
        collegesList.add("Hampton University");
        collegesList.add("University of Hartford");
        collegesList.add("Hartwick College");
        collegesList.add("Harvard University");
        collegesList.add("Harvey Mudd College | HMC");
        collegesList.add("Haverford College");
        collegesList.add("Hendrix College");
        collegesList.add("High Point University");
        collegesList.add("Hillsdale College");
        collegesList.add("Hiram College");
        collegesList.add("Hobart and William Smith Colleges | HWS");
        collegesList.add("Hofstra University");
        collegesList.add("Hollins University");
        collegesList.add("College of the Holy Cross");
        collegesList.add("Hope College");
        collegesList.add("University of Houston");
        collegesList.add("Howard Payne University | HPU");
        collegesList.add("Howard University");
        collegesList.add("Humboldt State University | HSU");

        collegesList.add("University of Illinois - Chicago | UIC");
        collegesList.add("University of Illinois - Urbana-Champaign | UIUC");
        collegesList.add("Indiana University - Bloomington | Indiana");
        collegesList.add("Indiana University - Northwest | IU Northwest");
        collegesList.add("Indiana University of Pennsylvania | IUP");
        collegesList.add("Indiana University-Purdue University Indianapolis | IUPUI");
        collegesList.add("Indiana University - South Bend");
        collegesList.add("Indiana State University | ISU");
        collegesList.add("University of Iowa");
        collegesList.add("Iowa State University");
        collegesList.add("Illinois Wesleyan University");
        collegesList.add("Illinois Institute of Technology | Illinois Tech");
        collegesList.add("Illinois State University | ISU");
        collegesList.add("Ithaca College");

        collegesList.add("Jackson State University | JSU");
        collegesList.add("James Madison University | JMU");
        collegesList.add("John Carroll University | JCU");
        collegesList.add("Johns Hopkins University | JHU");
        collegesList.add("The Juilliard School");
        collegesList.add("Juniata College");

        collegesList.add("Kalamazoo College");
        collegesList.add("University of Kansas");
        collegesList.add("Kansas State University | KSU");
        collegesList.add("Kennesaw State University | KSU");
        collegesList.add("Kent State University");
        collegesList.add("University of Kentucky");
        collegesList.add("Kenyon College");
        collegesList.add("Knox College");

        collegesList.add("Lafayette College");
        collegesList.add("Laguna College of Art and Design | LCAD");
        collegesList.add("Lake Forest College");
        collegesList.add("LaSalle University");
        collegesList.add("Lasell College | LC");
        collegesList.add("Lawrence University");
        collegesList.add("Lehigh University");
        collegesList.add("Lewis & Clark College");
        collegesList.add("Linfield College");
        collegesList.add("Louisiana State University");
        collegesList.add("University of Louisville");
        collegesList.add("Loyola University of Chicago");
        collegesList.add("Loyola University - Maryland");
        collegesList.add("Loyola University - New Orleans");
        collegesList.add("Loyola Marymount University");
        collegesList.add("University of Lynchburg");

        collegesList.add("Macalester College");
        collegesList.add("University of Maine");
        collegesList.add("Manhattan College");
        collegesList.add("Manhattanville College");
        collegesList.add("Marietta College");
        collegesList.add("Marist College");
        collegesList.add("Marlboro College");
        collegesList.add("Marquette University");
        collegesList.add("University of Mary Washington");
        collegesList.add("University of Maryland - Baltimore County | UMD Baltimore County");
        collegesList.add("University of Maryland - College Park | UMD College Park");
        collegesList.add("Marymount Manhattan College");
        collegesList.add("University of Massachusetts - Amherst");
        collegesList.add("University of Massachusetts - Boston");
        collegesList.add("Massachusetts Institute of Technology");
        collegesList.add("McGill University");
        collegesList.add("Mercer University");
        collegesList.add("Merrimack College");
        collegesList.add("University of Miami - Florida");
        collegesList.add("Miami University - Ohio");
        collegesList.add("University of Michigan | UMICH");
        collegesList.add("Michigan State University | MSU");
        collegesList.add("Michigan Technological University");
        collegesList.add("Middlebury College");
        collegesList.add("Mills College");
        collegesList.add("Millsaps College");
        collegesList.add("University of Minnesota");
        collegesList.add("University of Mississippi");
        collegesList.add("Mississippi State University");
        collegesList.add("University of Missouri - Columbia");
        collegesList.add("University of Missouri - Kansas City");
        collegesList.add("Missouri University of Science and Technology");
        collegesList.add("Monmouth University");
        collegesList.add("University of Montana");
        collegesList.add("Montclair State University");
        collegesList.add("Moravian College");
        collegesList.add("Morehouse College");
        collegesList.add("Mount Holyoke College");
        collegesList.add("Muhlenberg College");

        collegesList.add("University of Nebraska");
        collegesList.add("University of Nevada");
        collegesList.add("New College of Florida");
        collegesList.add("New England College");
        collegesList.add("University of New Hampshire");
        collegesList.add("University of New Haven");
        collegesList.add("The College of New Jersey");
        collegesList.add("New Jersey Institute of Technology | NJIT");
        collegesList.add("New Mexico Institute of Mining & Technology");
        collegesList.add("University of New Mexico");
        collegesList.add("University of New Orleans");
        collegesList.add("New York University");
        collegesList.add("University of North Carolina - Asheville | UNC Asheville");
        collegesList.add("University of North Carolina - Chapel Hill | UNC Chapel Hill");
        collegesList.add("University of North Carolina - Charlotte | UNC Charlotte");
        collegesList.add("University of North Carolina - Greensboro | UNC Greensboro");
        collegesList.add("University of North Carolina - Wilmington | UNC Wilmington");
        collegesList.add("North Carolina School of the Arts");
        collegesList.add("North Carolina State University | NC State");
        collegesList.add("University of North Dakota");
        collegesList.add("University of North Florida");
        collegesList.add("Northeastern University");
        collegesList.add("Northern Arizona University");
        collegesList.add("Northwestern University");
        collegesList.add("University of Notre Dame | UND");

        collegesList.add("Oberlin College");
        collegesList.add("Occidental College");
        collegesList.add("Oglethorpe University");
        collegesList.add("Ohio University");
        collegesList.add("Ohio Northern University");
        collegesList.add("Ohio State University | OSU");
        collegesList.add("Ohio Wesleyan University");
        collegesList.add("University of Oklahoma");
        collegesList.add("Oklahoma State University");
        collegesList.add("Old Dominion University");
        collegesList.add("Olin College");
        collegesList.add("University of Oregon");
        collegesList.add("Oregon State University | OSU");

        collegesList.add("Pace University");
        collegesList.add("University of the Pacific");
        collegesList.add("Parsons School of Design");
        collegesList.add("Penn State");
        collegesList.add("University of Pennsylvania | UPenn");
        collegesList.add("Pepperdine University");
        collegesList.add("Philadelphia University");
        collegesList.add("University of Pittsburgh");
        collegesList.add("Pitzer College");
        collegesList.add("Pomona College");
        collegesList.add("Pratt Institute");
        collegesList.add("Princeton University");
        collegesList.add("Providence College");
        collegesList.add("University of Puget Sound");
        collegesList.add("Purdue University");

        collegesList.add("Queens University - Kingston, Ontario");
        collegesList.add("Quinnipiac University");

        collegesList.add("Randolph College");
        collegesList.add("Randolph-Macon College");
        collegesList.add("University of Redlands");
        collegesList.add("Reed College");
        collegesList.add("Regis University");
        collegesList.add("Rensselaer Polytechnic Institute | RPI");
        collegesList.add("University of Rhode Island");
        collegesList.add("Rhode Island School of Design");
        collegesList.add("Rhodes College");
        collegesList.add("Rice University");
        collegesList.add("University of Richmond");
        collegesList.add("Rider University");
        collegesList.add("Ripon College");
        collegesList.add("University of Rochester");
        collegesList.add("Rochester Institute of Technology | RIT");
        collegesList.add("Rollins College");
        collegesList.add("Rose-Hulman Institute of Technology");
        collegesList.add("Rowan University");
        collegesList.add("Rutgers University");

        collegesList.add("Sacred Heart University");
        collegesList.add("College of Saint Benedict and Saint John's University");
        collegesList.add("St. Bonaventure University");
        collegesList.add("St. John's College - Maryland");
        collegesList.add("St. John's College - New Mexico");
        collegesList.add("St. John's University (New York)");
        collegesList.add("Saint Joseph's University");
        collegesList.add("St. Lawrence University");
        collegesList.add("Saint Louis University");
        collegesList.add("Saint Mary's College of California");
        collegesList.add("St. Mary's College of Maryland");
        collegesList.add("Saint Mary's College - Notre Dame");
        collegesList.add("Saint Michael's College");
        collegesList.add("Saint Olaf College");
        collegesList.add("Salisbury University");
        collegesList.add("Salve Regina University");
        collegesList.add("Samford University");
        collegesList.add("University of San Diego");
        collegesList.add("San Diego State University");
        collegesList.add("San Francisco State University");
        collegesList.add("University of San Francisco");
        collegesList.add("San Jose State University");
        collegesList.add("Santa Clara University");
        collegesList.add("Sarah Lawrence College");
        collegesList.add("Savannah College of Art and Design");
        collegesList.add("School of Visual Arts");
        collegesList.add("University of Scranton");
        collegesList.add("Saint Anselm College");
        collegesList.add("Scripps College");
        collegesList.add("Seattle University");
        collegesList.add("Seton Hall University | SHU");
        collegesList.add("Sewanee: The University of the South");
        collegesList.add("Shimer College");
        collegesList.add("Siena College");
        collegesList.add("Simmons College");
        collegesList.add("Simon's Rock College of Bard");
        collegesList.add("Skidmore College");
        collegesList.add("Smith College");
        collegesList.add("Soka University of America");
        collegesList.add("Sonoma State University");
        collegesList.add("University of South Carolina | USC");
        collegesList.add("University of South Florida | USF");
        collegesList.add("University of Southern California | USC");
        collegesList.add("Southern Methodist University");
        collegesList.add("Southwestern University");
        collegesList.add("Spelman College");
        collegesList.add("Stanford University");
        collegesList.add("Stephens College");
        collegesList.add("Stetson University");
        collegesList.add("Stevens Institute of Technology");
        collegesList.add("Stevenson University");
        collegesList.add("Stonehill College");
        collegesList.add("SUNY at Albany | SUNY Albany");
        collegesList.add("SUNY at Binghamton | SUNY Binghampton");
        collegesList.add("SUNY at Buffalo | SUNY Buffalo");
        collegesList.add("SUNY at Geneseo | SUNY Geneseo");
        collegesList.add("SUNY at Purchase | SUNY Purchase");
        collegesList.add("SUNY at Stony Brook | SUNY Stony Brook");
        collegesList.add("Susquehanna University");
        collegesList.add("Swarthmore College");
        collegesList.add("Sweet Briar College");
        collegesList.add("Syracuse University");

        collegesList.add("University of Tampa");
        collegesList.add("Temple University");
        collegesList.add("University of Tennessee");
        collegesList.add("The University of Texas - GENERAL");
        collegesList.add("The University of Texas at Austin | UT Austin");
        collegesList.add("Texas A&M University");
        collegesList.add("TCU");
        collegesList.add("Texas Tech University");
        collegesList.add("Thomas Aquinas College - California");
        collegesList.add("University of Toronto");
        collegesList.add("Towson University");
        collegesList.add("Trinity College (Connecticut)");
        collegesList.add("Trinity University (Texas)");
        collegesList.add("Truman State University");
        collegesList.add("Tufts University");
        collegesList.add("Tulane University");
        collegesList.add("University of Tulsa");
        collegesList.add("Tuskegee University");

        collegesList.add("Union College - New York");
        collegesList.add("United States Air Force Academy");
        collegesList.add("United States Coast Guard Academy");
        collegesList.add("United States Merchant Marine Academy");
        collegesList.add("United States Military Academy");
        collegesList.add("United States Naval Academy");
        collegesList.add("University of the Sciences in Philadelphia");
        collegesList.add("Ursinus College");
        collegesList.add("Ursuline College");
        collegesList.add("University of Utah");

        collegesList.add("Valparaiso University");
        collegesList.add("Vanderbilt University");
        collegesList.add("Vassar College");
        collegesList.add("University of Vermont");
        collegesList.add("Villanova University");
        collegesList.add("University of Virginia | UVA");
        collegesList.add("Virginia Commonwealth University");
        collegesList.add("Virginia Tech");
        collegesList.add("Virginia Wesleyan College");

        collegesList.add("Wabash College");
        collegesList.add("Wagner College");
        collegesList.add("Wake Forest University");
        collegesList.add("Warren Wilson College");
        collegesList.add("University of Washington");
        collegesList.add("Washington and Lee University");
        collegesList.add("Washington State University");
        collegesList.add("Washington University in St. Louis");
        collegesList.add("University of Waterloo");
        collegesList.add("Webb Institute");
        collegesList.add("Wellesley College");
        collegesList.add("Wells College");
        collegesList.add("Wesleyan College");
        collegesList.add("Wesleyan University");
        collegesList.add("West Virginia University | WVU");
        collegesList.add("Western Michigan University");
        collegesList.add("Western Washington University");
        collegesList.add("Westminster College - Pennsylvania");
        collegesList.add("Wheaton College - Illinois");
        collegesList.add("Wheaton College - Massachusetts");
        collegesList.add("Whitman College");
        collegesList.add("Whittier College");
        collegesList.add("College of William and Mary");
        collegesList.add("Willamette University");
        collegesList.add("William Jewell College");
        collegesList.add("Williams College");
        collegesList.add("University of Wisconsin");
        collegesList.add("Wittenberg University");
        collegesList.add("Wofford College");
        collegesList.add("College of Wooster");
        collegesList.add("Worcester Polytechnic Institute | WPI");
        collegesList.add("Wright State University");
        collegesList.add("University of Wyoming");
        collegesList.add("Yale University");
        collegesList.add("Yeshiva University");
        collegesList.add("Xavier University");
    }

    public ArrayList<String> getCollegesList(){
        return collegesList;
    }

}
