package com.bindi.collegeplanner.databaseClasses;

import java.util.ArrayList;

public class MajorDb {

    public ArrayList<String> collegesList;

    public MajorDb(){
        collegesList = new ArrayList<String>();
        collegesList.add("I Did Not Find My Major");
        collegesList.add("Undecided");
        //Agriculture & Natural Resources Conservation
        collegesList.add("Agriculture");
        collegesList.add("Agribusiness Operations");
        collegesList.add("Agricultural Business & Management");
        collegesList.add("Agricultural Economics");
        collegesList.add("Agricultural Mechanization");
        collegesList.add("Agricultural Production");
        collegesList.add("Agronomy & Crop Science");
        collegesList.add("Animal Sciences");
        collegesList.add("Food Sciences & Technology");
        collegesList.add("Horticulture Operations & Management");
        collegesList.add("Horticulture Science");
        collegesList.add("Natural Resources Conservation, General");
        collegesList.add("Environmental Science");
        collegesList.add("Forestry");
        collegesList.add("Natural Resources Management");
        collegesList.add("Wildlife & Wildlands Management");
        //Architecture
        collegesList.add("Architecture");
        collegesList.add("Architectural Environmental Design");
        collegesList.add("City/Urban/Regional Planning");
        collegesList.add("Interior Architecture");
        collegesList.add("Landscape Architecture");
        //Area, Ethnic, and Multidisciplinary Studies
        collegesList.add("Area Studies, General");
        collegesList.add("Asian Area Studies");
        collegesList.add("European Area Studies");
        collegesList.add("Latin American Area Studies");
        collegesList.add("North American Area Studies");
        collegesList.add("Ethnic & Minority Studies, General");
        collegesList.add("African American Studies");
        collegesList.add("American Indian/Native American Studies");
        collegesList.add("Latino/Chicano Studies");
        collegesList.add("Women's Studies");
        collegesList.add("Liberal Arts & General Studies");
        collegesList.add("Library Science");
        collegesList.add("Interdisciplinary Studies");
        //Arts: Visual & Performing
        collegesList.add("Art");
        collegesList.add("Art History, Criticism & Conservation");
        collegesList.add("Fine/Studio Arts");
        collegesList.add("Cinema/Film");
        collegesList.add("Cinematography/Film/Video Production");
        collegesList.add("Dance");
        collegesList.add("Design & Visual Communications");
        collegesList.add("Fashion/Apparel Design");
        collegesList.add("Graphic Design");
        collegesList.add("Industrial Design");
        collegesList.add("Interior Design");
        collegesList.add("Music");
        collegesList.add("Musical Performance");
        collegesList.add("Music Theory & Composition");
        collegesList.add("Photography");
        collegesList.add("Theatre Arts/Drama");
        //Business
        collegesList.add("Accounting");
        collegesList.add("Accounting Technician");
        collegesList.add("Business Administration & Management, General");
        collegesList.add("Hotel/Motel Management");
        collegesList.add("Human Resources Development");
        collegesList.add("Human Resources Management");
        collegesList.add("Labor/Industrial Relations");
        collegesList.add("Logistics & Materials Management\n");
        collegesList.add("Marketing Management & Research");
        collegesList.add("Office Supervision & Management");
        collegesList.add("Operations Management & Supervision");
        collegesList.add("Organizational Behavior");
        collegesList.add("Purchasing/Procurement/Contracts Management");
        collegesList.add("Restaurant/Food Services Management");
        collegesList.add("Small Business Management/Operations");
        collegesList.add("Travel/Tourism Management");
        collegesList.add("Business/Management Quantitative Methods, General");
        collegesList.add("Actuarial Science");
        collegesList.add("Business/Managerial Economics");
        collegesList.add("Finance");
        collegesList.add("Banking & Financial Support Services");
        collegesList.add("Financial Planning & Services");
        collegesList.add("Insurance & Risk Management");
        collegesList.add("Investments & Securities");
        collegesList.add("Management Information Systems");
        collegesList.add("Real Estate");
        collegesList.add("Sales, Merchandising, & Marketing");
        collegesList.add("Fashion Merchandising");
        collegesList.add("Tourism & Travel Marketing");
        collegesList.add("Secretarial Studies & Office Administration");
        //Communications
        collegesList.add("Communications");
        collegesList.add("Advertising");
        collegesList.add("Digital Communications/Media");
        collegesList.add("Broadcast Journalism");
        collegesList.add("Print Journalism");
        collegesList.add("Mass Communications");
        collegesList.add("Public Relations & Organizational Communication");
        collegesList.add("Radio & Television Broadcasting");
        collegesList.add("Communications Technology");
        collegesList.add("Graphic & Printing Equipment Operation");
        collegesList.add("Multimedia/Animation/Special Effects");
        collegesList.add("Radio & Television Broadcasting Technology");
        //Community, Family, and Personal Services
        collegesList.add("Family & Consumer Sciences");
        collegesList.add("Adult Development & Aging/Gerontology");
        collegesList.add("Child Care Services Management");
        collegesList.add("Child Development");
        collegesList.add("Consumer & Family Economics");
        collegesList.add("Food & Nutrition");
        collegesList.add("Textile & Apparel");
        collegesList.add("Parks, Recreation, & Leisure, General");
        collegesList.add("Exercise Science/Physiology/Kinesiology");
        collegesList.add("Health & Physical Education/Fitness");
        collegesList.add("Parks/Rec/Leisure Facilities Management");
        collegesList.add("Sport & Fitness Administration/Management");
        collegesList.add("Personal Services");
        collegesList.add("Cosmetology/Hairstyling\n");
        collegesList.add("Culinary Arts");
        collegesList.add("Funeral Services");
        collegesList.add("Protective Services");
        collegesList.add("Corrections");
        collegesList.add("Criminal Justice");
        collegesList.add("Fire Protection & Safety Technology");
        collegesList.add("Law Enforcement");
        collegesList.add("Military Technologies");
        collegesList.add("Public Administration & Services");
        collegesList.add("Community Organization & Advocacy");
        collegesList.add("Public Administration");
        collegesList.add("Public Affairs & Public Policy Analysis");
        collegesList.add("Social Work");
        //Computer Science and Mathematics
        collegesList.add("Computer & Information Sciences");
        collegesList.add("Computer Science");
        collegesList.add("Computer Networking/Telecommunications");
        collegesList.add("Computer Science & Programming");
        collegesList.add("Computer Science & Engineering");
        collegesList.add("Computer Software & Media Applications");
        collegesList.add("Computer System Administration");
        collegesList.add("Data Management Technology");
        collegesList.add("Information Science");
        collegesList.add("Webpage Design");
        collegesList.add("Mathematics");
        collegesList.add("Applied Mathematics");
        collegesList.add("Statistics");
        //Education
        collegesList.add("Counseling & Student Services");
        collegesList.add("Educational Administration");
        collegesList.add("Special Education");
        collegesList.add("Teacher Education");
        collegesList.add("Curriculum & Instruction");
        collegesList.add("Early Childhood Education");
        collegesList.add("Elementary Education");
        collegesList.add("Junior High/Middle School Education");
        collegesList.add("Post-Secondary Education");
        collegesList.add("Secondary Education");
        collegesList.add("Teacher Assisting/Aide Education");
        collegesList.add("Agricultural Education");
        collegesList.add("Art Education");
        collegesList.add("Business Education");
        collegesList.add("Career & Technical Education");
        collegesList.add("English-As-A-Second-Language Education");
        collegesList.add("English/Language Arts Education");
        collegesList.add("Foreign Languages Education");
        collegesList.add("Health Education");
        collegesList.add("Mathematics Education");
        collegesList.add("Music Education");
        collegesList.add("Physical Education & Coaching");
        collegesList.add("Science Education");
        collegesList.add("Social Studies Education");
        collegesList.add("Social Sciences Education");
        //Engineering
        collegesList.add("Engineering");
        collegesList.add("Aerospace/Aeronautical Engineering");
        collegesList.add("Agricultural/Bioengineering");
        collegesList.add("Architectural Engineering");
        collegesList.add("Biomedical Engineering");
        collegesList.add("Chemical Engineering");
        collegesList.add("Civil Engineering");
        collegesList.add("Computer Engineering");
        collegesList.add("Construction Engineering/Management");
        collegesList.add("Electrical, Electronics & Communications Engineering");
        collegesList.add("Environmental Health Engineering");
        collegesList.add("Industrial Engineering");
        collegesList.add("Mechanical Engineering");
        collegesList.add("Nuclear Engineering");
        //Engineering Technology and Drafting
        collegesList.add("Drafting");
        collegesList.add("Architectural Drafting");
        collegesList.add("Mechanical Drafting");
        collegesList.add("CAD Technology");
        collegesList.add("Engineering Technology");
        collegesList.add("Aeronautical/Aerospace Engineering Technologies");
        collegesList.add("Architectural Engineering Technology");
        collegesList.add("Automotive Engineering Technology");
        collegesList.add("Civil Engineering Technology");
        collegesList.add("Computer Engineering Technology");
        collegesList.add("Construction/Building Technology");
        collegesList.add("Electrical, Electronics Engineering Technologies");
        collegesList.add("Electromechanical/Biomedical Engineering Technologies");
        collegesList.add("Environmental Control Technologies");
        collegesList.add("Industrial Production Technologies");
        collegesList.add("Mechanical Engineering Technology");
        collegesList.add("Quality Control & Safety Technologies");
        collegesList.add("Surveying Technology");
        //English and Foreign Languages
        collegesList.add("English Language & Literature");
        collegesList.add("American/English Literature");
        collegesList.add("Creative Writing");
        collegesList.add("Public Speaking");
        collegesList.add("Foreign Languages/Literature");
        collegesList.add("Asian Languages/Literature");
        collegesList.add("Classical/Ancient Languages/Literature");
        collegesList.add("Comparative Literature");
        collegesList.add("French Language/Literature");
        collegesList.add("German Language/Literature");
        collegesList.add("Linguistics");
        collegesList.add("Middle Eastern Languages/Literature");
        collegesList.add("Spanish Language/Literature");
        //Health Administration and Assisting
        collegesList.add("Health Services Administration");
        collegesList.add("Hospital/Facilities Administration");
        collegesList.add("Medical Office/Secretarial");
        collegesList.add("Medical Records");
        collegesList.add("Medical/Clinical Assisting");
        collegesList.add("Dental Assisting");
        collegesList.add("Medical Assisting");
        collegesList.add("Occupational Therapy Assisting");
        collegesList.add("Physical Therapy Assisting");
        collegesList.add("Veterinarian Assisting/Technology");
        //Health Sciences and Technologies
        collegesList.add("Chiropractic");
        collegesList.add("Dental Hygiene");
        collegesList.add("Dentistry");
        collegesList.add("Emergency Medical Technology");
        collegesList.add("Health-Related Professions & Services");
        collegesList.add("Athletic Training");
        collegesList.add("Communication Disorder Services");
        collegesList.add("Public Health");
        collegesList.add("Health/Medical Technology");
        collegesList.add("Medical Laboratory Technology");
        collegesList.add("Medical Radiologic Technology");
        collegesList.add("Nuclear Medicine Technology");
        collegesList.add("Respiratory Therapy Technology");
        collegesList.add("Surgical Technology");
        collegesList.add("Medicine");
        collegesList.add("Nursing");
        collegesList.add("Optometry");
        collegesList.add("Osteopathic Medicine");
        collegesList.add("Pharmacy");
        collegesList.add("Physician Assisting");
        collegesList.add("Therapy & Rehabilitation");
        collegesList.add("Alcohol/Drug Abuse Counseling");
        collegesList.add("Massage Therapy");
        collegesList.add("Mental Health Counseling");
        collegesList.add("Occupational Therapy");
        collegesList.add("Physical Therapy");
        collegesList.add("Psychiatric/Mental Health Technician");
        collegesList.add("Rehabilitation Therapy");
        collegesList.add("Vocational Rehabilitation Counseling");
        collegesList.add("Veterinary Medicine");
        //Philosophy, Religion, and Theology
        collegesList.add("Philosophy");
        collegesList.add("Religion");
        collegesList.add("Theology");
        collegesList.add("Biblical Studies");
        collegesList.add("Ministry");
        collegesList.add("Religious Education");
        //Repair, Production and Construction
        collegesList.add("Aviation & Airway Science");
        collegesList.add("Aircraft Piloting & Navigation");
        collegesList.add("Aviation Management & Operations");
        collegesList.add("Construction Trades");
        collegesList.add("Mechanics & Repairers");
        collegesList.add("Aircraft Mechanics/Technology");
        collegesList.add("Autobody Repair/Technology");
        collegesList.add("Automotive Mechanics/Technology");
        collegesList.add("Avionics Technology");
        collegesList.add("Diesel Mechanics/Technology");
        collegesList.add("Electrical/Electronics Equip Installation & Repair");
        collegesList.add("Heating/Air Conditioner/Refrigeration Install/Repair");
        collegesList.add("Precision Production Trades");
        collegesList.add("Machine Tool Technology");
        collegesList.add("Welding Technology");
        collegesList.add("Transportation & Materials Moving");
        //Biological and Physical
        collegesList.add("Biology");
        collegesList.add("Biochemistry & Biophysics");
        collegesList.add("Cellular Biology");
        collegesList.add("Ecology");
        collegesList.add("Genetics");
        collegesList.add("Marine/Aquatic Biology");
        collegesList.add("Microbiology & Immunology");
        collegesList.add("Zoology");
        collegesList.add("Physical Sciences");
        collegesList.add("Astronomy");
        collegesList.add("Atmospheric Sciences & Meteorology");
        collegesList.add("Chemistry");
        collegesList.add("Geological & Earth Sciences");
        collegesList.add("Physics");
        //Social Sciences and Law
        collegesList.add("Legal Studies");
        collegesList.add("Court Reporting");
        collegesList.add("Law");
        collegesList.add("Legal Administrative Assisting");
        collegesList.add("Legal Assistant");
        collegesList.add("Social Sciences");
        collegesList.add("Anthropology");
        collegesList.add("Criminology");
        collegesList.add("Economics");
        collegesList.add("Geography");
        collegesList.add("History");
        collegesList.add("International Relations & Affairs");
        collegesList.add("Political Science & Government");
        collegesList.add("Psychology, Clinical & Counseling");
        collegesList.add("Psychology");
        collegesList.add("Sociology");
        collegesList.add("Urban Studies");
    }

    public ArrayList<String> getTypesList(){
        return collegesList;
    }

}
